// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations

import ballerina/http;
import ballerina/os;
import ballerina/test;

final boolean isLiveServer = os:getEnv("IS_LIVE_SERVER") == "true";
final string serviceUrl = isLiveServer ? "https://api.app.shortcut.com/api/v3" : "http://localhost:9090";
final string token = isLiveServer ? os:getEnv("SHORTCUT_API_TOKEN") : "test_token";

final Client shortcut = check new ({shortcutToken: token}, {httpVersion: http:HTTP_1_1}, serviceUrl);

@test:Config {groups: ["live_tests", "mock_tests"]}
function testListCategories() returns error? {
    Category[] response = check shortcut->listCategories();
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testCreateCategory() returns error? {
    Category response = check shortcut->createCategory({name: "Platform"});
    test:assertEquals(response.name, "Platform");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testGetCategory() returns error? {
    Category response = check shortcut->getCategory(1);
    test:assertEquals(response.id, 1);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testUpdateCategory() returns error? {
    Category response = check shortcut->updateCategory(1, {name: "Platform Engineering"});
    test:assertEquals(response.name, "Platform Engineering");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testDeleteCategory() returns error? {
    if isLiveServer {
        return;
    }
    Category created = check shortcut->createCategory({name: "Temporary"});
    check shortcut->deleteCategory(created.id);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testListEpics() returns error? {
    EpicSlim[] response = check shortcut->listEpics();
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testCreateEpic() returns error? {
    Epic response = check shortcut->createEpic({name: "Q4 Roadmap"});
    test:assertEquals(response.name, "Q4 Roadmap");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testGetEpic() returns error? {
    Epic response = check shortcut->getEpic(101);
    test:assertEquals(response.id, 101);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testUpdateEpic() returns error? {
    Epic response = check shortcut->updateEpic(101, {name: "Q4 Roadmap Updated"});
    test:assertEquals(response.name, "Q4 Roadmap Updated");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testDeleteEpic() returns error? {
    if isLiveServer {
        return;
    }
    Epic created = check shortcut->createEpic({name: "Temporary epic"});
    check shortcut->deleteEpic(created.id);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testCreateStory() returns error? {
    Story response = check shortcut->createStory({name: "Add SSO support"});
    test:assertEquals(response.name, "Add SSO support");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testGetStory() returns error? {
    Story response = check shortcut->getStory(401);
    test:assertEquals(response.id, 401);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testUpdateStory() returns error? {
    Story response = check shortcut->updateStory(401, {name: "Add SSO support v2"});
    test:assertEquals(response.name, "Add SSO support v2");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testDeleteStory() returns error? {
    if isLiveServer {
        return;
    }
    Story created = check shortcut->createStory({name: "Temporary story"});
    check shortcut->deleteStory(created.id);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testListLabels() returns error? {
    Label[] response = check shortcut->listLabels();
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testCreateLabel() returns error? {
    Label response = check shortcut->createLabel({name: "tech-debt"});
    test:assertEquals(response.name, "tech-debt");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testGetLabel() returns error? {
    Label response = check shortcut->getLabel(301);
    test:assertEquals(response.id, 301);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testListMembers() returns error? {
    Member[] response = check shortcut->listMembers();
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testGetMember() returns error? {
    Member response = check shortcut->getMember("5f9b3c1e-7a2d-4c1b-9e61-0a1b2c3d4e5f");
    test:assertEquals(response.id, "5f9b3c1e-7a2d-4c1b-9e61-0a1b2c3d4e5f");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testListWorkflows() returns error? {
    Workflow[] response = check shortcut->listWorkflows();
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testGetWorkflow() returns error? {
    Workflow response = check shortcut->getWorkflow(501);
    test:assertEquals(response.id, 501);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testListIterations() returns error? {
    IterationSlim[] response = check shortcut->listIterations();
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testCreateIteration() returns error? {
    Iteration response = check shortcut->createIteration({name: "Sprint 44", startDate: "2024-07-01", endDate: "2024-07-14"});
    test:assertEquals(response.name, "Sprint 44");
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testGetIteration() returns error? {
    Iteration response = check shortcut->getIteration(201);
    test:assertEquals(response.id, 201);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testSearchStories() returns error? {
    StorySearchResults response = check shortcut->searchStories(query = "login");
    test:assertTrue(response.data.length() > 0);
}
